### ISSUE TITLE
STARE::ValueFromLatLonDegrees returning level instead of index when declared as global variable

### ISSUE THREAD

**Issue by NiklasPhabian** [michaelleerilee/STARE#22]
Quite possible that I don't understand c++ scopes; however, this is surprising to me. This works as expected:

```
#include "STARE.h"

int main(int argc, char *argv[]) {    
    STARE stare;
    cout << " " << stare.ValueFromLatLonDegrees(10.1, 15.2, 10) << endl;
    cout << " " << stare.ValueFromLatLonDegrees(10.1, 15.2, 15) << endl;    
} 
```

This doesn't (it returns the depth rather than the STARE id)

```
#include "STARE.h"

STARE stare;
int main(int argc, char *argv[]) {    
    cout << " " << ::stare.ValueFromLatLonDegrees(10.1, 15.2, 10) << endl;
    cout << " " << ::stare.ValueFromLatLonDegrees(10.1, 15.2, 15) << endl;    
} 
```

**Comment by michaelleerilee** [comment]
Interesting. Thanks for posting this. It could be something isn't being initialized or is being initialized and then being freed. I seem to recall that some parts of the code return zero as an error code, and if that isn't checked it might show up like this. Or an algorithm is failing underneath, returning a zero incorrectly. I'll see if I can add this to the tests.

**Comment by michaelleerilee** [comment]
I've replicated the bug in a test.

**Comment by michaelleerilee** [comment]
I guess in the second case the compiler is interpreting stare as a declaration.

**Comment by michaelleerilee** [comment]
I believe that stare is being initialized during static initialization while the SpatialVectors xhat and yhat are being defined during dynamic initialization, i.e., after stare is initialized, corrupting stare.

**Comment by michaelleerilee** [comment]
Fixed by declaring SpatialVectors xhat, etc., locally. Cf. https://github.com/michaelleerilee/STARE/releases/tag/0.5.2-beta .
